apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      labels:
        app: my_app
    spec:
      containers:
      - name: my_app
        image: kgiriraj/nginx:0.2.0
        ports:
        - containerPort: 80
