apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: kgiriraj/nginx:0.2.0
        ports:
        - containerPort: 80
